import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import {NextIntlClientProvider, useMessages, useLocale} from 'next-intl';
import { notFound } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({ children, params }: RootLayoutProps) {
  const locale  = useLocale();
  const messages = useMessages();
  
  if(params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <body className={"${inter.className} relative flex min-h-screen flex-col bg-background"}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        {children}
        </ThemeProvider>
      </body>
      </NextIntlClientProvider>
    </html>
  )
}
